import { invalidateStatsCache } from "@/lib/stats";
import { NextRequest,NextResponse } from "next/server";
import { adminDb } from "@/lib/firebase-admin";
import { requireAdmin,UnauthorizedError } from "@/lib/require-admin";
import { ensureDefaultScrutin,getActiveScrutin,invalidateActiveScrutinCache } from "@/lib/scrutin";
import { FieldValue } from "firebase-admin/firestore";
async function guard(r:NextRequest){try{return await requireAdmin(r)}catch(e){if(e instanceof UnauthorizedError)return NextResponse.json({ok:false,error:e.message},{status:401});throw e}}
export async function GET(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;await ensureDefaultScrutin();const [snap,active]=await Promise.all([adminDb.collection("scrutins").get(),getActiveScrutin()]);const scrutins=snap.docs.map(d=>({id:d.id,...d.data()})).sort((x:any,y:any)=>String(y.dateCreation).localeCompare(String(x.dateCreation)));return NextResponse.json({ok:true,scrutins,actifId:active.id});}
export async function POST(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;const b=await r.json();const titre=String(b.titre||"").trim();if(!titre)return NextResponse.json({ok:false,error:"titre_requis"},{status:400});const ref=await adminDb.collection("scrutins").add({titre,type:b.type==="OFFICIEL"?"OFFICIEL":"TEST",statut:"FERME",actif:false,archive:false,dateCreation:new Date().toISOString(),dateOuverture:null,dateFermeture:null});await adminDb.collection("journalAdmin").add({action:"creation_scrutin",detail:`${ref.id} - ${titre}`,date:FieldValue.serverTimestamp(),admin:(a as any).email??(a as any).uid});return NextResponse.json({ok:true,id:ref.id});}
export async function PUT(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;const b=await r.json();const id=String(b.id||"");if(!id)return NextResponse.json({ok:false,error:"id_requis"},{status:400});if(b.action==="activer"){const old=await getActiveScrutin();const batch=adminDb.batch();batch.set(adminDb.collection("configuration").doc("etat"),{scrutinActifId:id},{merge:true});batch.set(adminDb.collection("scrutins").doc(old.id),{actif:false},{merge:true});batch.set(adminDb.collection("scrutins").doc(id),{actif:true},{merge:true});await batch.commit();}else{const updates:any={};if(typeof b.titre==="string"&&b.titre.trim())updates.titre=b.titre.trim();if(b.type==="TEST"||b.type==="OFFICIEL")updates.type=b.type;if(typeof b.archive==="boolean")updates.archive=b.archive;await adminDb.collection("scrutins").doc(id).set(updates,{merge:true});}invalidateActiveScrutinCache();invalidateStatsCache();await adminDb.collection("journalAdmin").add({action:"modification_scrutin",detail:id,date:FieldValue.serverTimestamp(),admin:(a as any).email??(a as any).uid});return NextResponse.json({ok:true});}
export async function DELETE(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;const id=new URL(r.url).searchParams.get("id");if(!id)return NextResponse.json({ok:false,error:"id_requis"},{status:400});const active=await getActiveScrutin();if(active.id===id)return NextResponse.json({ok:false,error:"scrutin_actif"},{status:409});const s=await adminDb.collection("scrutins").doc(id).get();if(s.data()?.type!=="TEST")return NextResponse.json({ok:false,error:"seul_test_supprimable"},{status:409});for(const c of ["votes","participations","candidats"]){const q=await adminDb.collection(c).where("scrutinId","==",id).get();for(let i=0;i<q.docs.length;i+=400){const batch=adminDb.batch();q.docs.slice(i,i+400).forEach(d=>batch.delete(d.ref));await batch.commit();}}await s.ref.delete();return NextResponse.json({ok:true});}
