import { NextRequest,NextResponse } from "next/server";
import { adminDb } from "@/lib/firebase-admin";
import { requireAdmin,UnauthorizedError } from "@/lib/require-admin";
import { normalizeMatricule } from "@/lib/matricule";
import { FieldValue } from "firebase-admin/firestore";
async function guard(r:NextRequest){try{return await requireAdmin(r)}catch(e){if(e instanceof UnauthorizedError)return NextResponse.json({ok:false,error:e.message},{status:401});throw e}}
export async function GET(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;const snap=await adminDb.collection("electeurs").orderBy("nom").limit(1000).get();return NextResponse.json({ok:true,electeurs:snap.docs.map(d=>({id:d.id,...d.data()}))});}
export async function POST(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;const b=await r.json();const matricule=String(b.matricule||"").trim(),nom=String(b.nom||"").trim(),prenom=String(b.prenom||"").trim();if(!matricule||!nom)return NextResponse.json({ok:false,error:"champs_requis"},{status:400});const n=normalizeMatricule(matricule);const q=await adminDb.collection("electeurs").where("matriculeNormalise","==",n).limit(1).get();if(!q.empty)return NextResponse.json({ok:false,error:"matricule_existant"},{status:409});await adminDb.collection("electeurs").doc(matricule).set({matricule,matriculeNormalise:n,nom,prenom,aVote:false,dateVote:null});await adminDb.collection("journalAdmin").add({action:"ajout_electeur",detail:matricule,date:FieldValue.serverTimestamp(),admin:(a as any).email??(a as any).uid});return NextResponse.json({ok:true});}
export async function DELETE(r:NextRequest){const a=await guard(r);if(a instanceof NextResponse)return a;const id=new URL(r.url).searchParams.get("id");if(!id)return NextResponse.json({ok:false,error:"id_requis"},{status:400});const p=await adminDb.collection("participations").where("electeurId","==",id).limit(1).get();if(!p.empty)return NextResponse.json({ok:false,error:"electeur_a_deja_participe"},{status:409});await adminDb.collection("electeurs").doc(id).delete();await adminDb.collection("journalAdmin").add({action:"suppression_electeur",detail:id,date:FieldValue.serverTimestamp(),admin:(a as any).email??(a as any).uid});return NextResponse.json({ok:true});}
